kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-delos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_delos_pod2
  template:
    metadata:
      labels:
        app: service_delos_pod2
    spec:
      containers:
      - name: simple-http
        image: python:2.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo \"POD2: I got it, roger\" > index.html; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080